initial change of usage and description
sonr-io/speedway pull request #127
Opened 2022-09-08 20:56 UTC by 6missedcalls

Refactor of the CLI command descriptions and usage. 
## Changes

- ```speedway object get``` command changed to ```speedway object query```

## API Updates

### New Features *(required)*
N/A

### Deprecations *(required)*
N/A

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-09-09 15:11 UTC, ntindle approved these changes

2022-09-12 17:06 UTC, joshLong145 requested changes

2022-09-12 17:06 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/object/object.go
> +		You can create a new object with the 'build' subcommand.
you can remove the "you can"

2022-09-12 17:06 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/object/object.go
> +		You can query an existing object with the 'query' subcommand.`,
can remove "you can"

2022-09-12 17:06 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/registry/Login.go
> +		You may be also be prompted to enter your computer password to allow Speedway to access a keypair for you.`,
you can remove "you will" and "you may"

2022-09-12 17:06 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/registry/Registry.go
> +		You can create a new account or login to an existing account.
you can remove "you can"

2022-09-12 17:06 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/registry/register.go
> +		You will also be prompted to enter your computer password to allow Speedway to create a new keypair for you. (Please do not delete this keypair from your keychain.)`,
you can remove "You will" and "You can"

2022-09-12 17:06 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/schema/schema.go
> +		You can query an existing schema with the 'query' subcommand.`,
you can remove "you can"

2022-09-12 17:23 UTC, mcjcloud approved these changes

2022-09-12 20:57 UTC, merged