Feat/parse
sonr-io/speedway pull request #134
Opened 2022-09-09 22:49 UTC by 6missedcalls

Added Schema parser for schema definition 
## Changes

- Input for Create Schema (CLI) changed from select prompt to a single prompt for all fields. Example: "name:string,age:int"
- Output for Create Schema (CLI) changed to reflect the documentation [here](https://www.sonr.dev/docs/guides/data/schemas#creating-a-schema)

## API Updates

### New Features *(required)*
N/A

### Deprecations *(required)*
N/A

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes #125 
Connects

2022-09-12 22:20 UTC, joshLong145 requested changes

2022-09-12 22:20 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/schema/create.go
> +				fieldsPrompt := promptui.Prompt{
I think should be passed an arg to create such that it only prompts if no arg is found.

2022-09-12 22:20 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/schema/create.go
> +					kind := utils.ConvertSchemaKind(fieldSplit[1])
convert might also need to return an error now because kind input is arbitrary.

2022-09-12 22:20 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/schema/create.go
Should use logger instead of fmt

2022-09-13 15:08 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/schema/create.go
> +				fieldsPrompt := promptui.Prompt{
Instead of prompt here, we could just take this as the default args? Is there any other info we need to collect?

2022-09-14 19:44 UTC, mcjcloud approved these changes

2022-09-15 18:06 UTC, ntindle approved these changes

2022-09-15 20:12 UTC, merged