Feature/base api env
sonr-io/speedway pull request #135
Opened 2022-09-12 13:17 UTC by Stefuu

Making base api configurable with env variables

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-09-12 14:50 UTC, tgfassina requested changes

2022-09-12 14:50 UTC, tgfassina commented on .env
> +REACT_APP_API_PATH=/api/v1
Do we need all these configs?
I think we can get away with just 1 flag. Something like: `DEV_MODE=true`
If it is false or empty, then the base api path is empty string, so all calls are made with relative path.
If it is true, then the base api path is `localhost:3001` (can be any port now. we just need to update the server.js port accordingly)

2022-09-12 16:19 UTC, joshLong145 commented on .env
> +REACT_APP_API_PATH=/api/v1
i like the explicit configuration options. is there a case where having more config options is a disadvantage?

2022-09-12 16:34 UTC, Stefuu commented on .env
> +REACT_APP_API_PATH=/api/v1
@tgfassina the REACT_APP_API_PATH is nice because we can easily change api version if we need, if we have a v2 in the future. 

And the REACT_APP_ORIGIN is needed because some of the api calls don't use the same base api path, so if we set the base api path to localhost:3001/api/v1 it would break the api calls that don't have /api/v1 in their path, thats why we need two separate variables, one for origin and one for base api path

Also i agree with @joshLong145 as long as the options are actually optional, meaning, if you just ignore them things will still work

2022-09-12 18:02 UTC, tgfassina commented on .env
> +REACT_APP_API_PATH=/api/v1
I think we should have as many configs as needed to fix the problem. Since we're now switching to relative paths, everything works just fine with the real server, no configs needed. What we want is to have the convenience of running it in a development mode with the server.js. Also, because dev mode happens by running `npm start`, the command itself can inject the variable and we don't event need to have this config file :]

2022-09-12 22:17 UTC, joshLong145 commented on .env
> +REACT_APP_API_PATH=/api/v1
> What we want is to have the convenience of running it in a development mode with the server.js. 

`server.js` is a debugging tool and probably should dictate what configuration options are needed for running in a real server scenerio. would having these options effect the dev server?

2022-09-13 17:55 UTC, tgfassina approved these changes

2022-09-13 17:56 UTC, merged