Feat/alias
sonr-io/speedway pull request #140
Opened 2022-09-13 21:29 UTC by 6missedcalls

Added Buy, Sell & Transfer Alias to the Command Line and API.
## Changes

- Updated go.mod to latest version of Sonr

## API Updates

### New Features *(required)*
N/A

### Deprecations *(required)*
N/A

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes #137 
Connects

2022-09-14 15:50 UTC, joshLong145 requested changes

2022-09-14 15:50 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +	return nil
we might want to do this on chain and not through the client @ntindle what do you think?

2022-09-14 15:50 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			}
I feel the wording here is a bit innacurrate. when you "sell" an alias you dont actually sell it. you are putting it in a state where it can be sold for the price you are listing for. so perhaps "Alias has been listed" or "Alias listed at price: <price user has given>"

2022-09-14 15:50 UTC, joshLong145 commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +				price, err = strconv.Atoi(priceStr)
we might want to check that the value is greater than 0

2022-09-14 18:48 UTC, joshLong145 approved these changes

2022-09-14 19:07 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +		Run: func(cmd *cobra.Command, args []string) {
Is Alias validated if passed from command line?

2022-09-14 19:07 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			if price, err = cmd.Flags().GetInt("price"); err == nil && price <= 0 {
I’m certain there are funky number things that can happen here

2022-09-14 19:07 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +		Run: func(cmd *cobra.Command, args []string) {
Validate cmd line alias

2022-09-14 19:07 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			if amount, err = cmd.Flags().GetInt("amount"); err == nil && amount == 0 {
Do transfers have a price

2022-09-14 19:08 UTC, 6missedcalls commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +		Run: func(cmd *cobra.Command, args []string) {
Yes it is, the validateAlias function is on line 20 of alias.go

2022-09-14 19:10 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +		Run: func(cmd *cobra.Command, args []string) {
I thought that only happens if name is empty though?

2022-09-14 19:11 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +	return nil
This should be done in chain already

2022-09-14 19:11 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			}
List Alias?

2022-09-14 19:12 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			}
That’s not Ian’s fault though… speedway UI should use that wording

2022-09-14 19:12 UTC, 6missedcalls commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			if amount, err = cmd.Flags().GetInt("amount"); err == nil && amount == 0 {
No they do not have a price, transfer alias has an amount of the alias to be transferred.

2022-09-14 19:13 UTC, ntindle commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			if amount, err = cmd.Flags().GetInt("amount"); err == nil && amount == 0 {
Oh wtf file an issue to discuss Alias api endpoints on Sonr

2022-09-14 19:46 UTC, 6missedcalls commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			if amount, err = cmd.Flags().GetInt("amount"); err == nil && amount == 0 {
https://github.com/sonr-io/sonr/issues/589

2022-09-14 19:55 UTC, mcjcloud commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			var name string = ""
nit: name will have value `""` by default.

2022-09-14 20:01 UTC, 6missedcalls commented on cmd/speedway-cli/speedwaycmd/registry/alias.go
> +			var name string = ""
Corrected, thank you!

2022-09-15 14:39 UTC, joshLong145 commented
@6missedcalls before merging please remove "transfer-alias" and "sell-alias" commands for now

2022-09-15 14:40 UTC, ntindle commented
> @6missedcalls before merging please remove "transfer-alias" and "sell-alias" commands for now

Can I get justification for this?

2022-09-15 15:44 UTC, joshLong145 approved these changes

2022-09-15 16:53 UTC, ma-sonr approved these changes

2022-09-15 18:07 UTC, merged