Query buckets by creator
sonr-io/speedway pull request #166
Opened 2022-09-20 02:03 UTC by tgfassina

Now we no longer need to pull all the buckets to then filter down the ones belonging to the logged-in user

2022-09-20 13:46 UTC, joshLong145 commented
@tgfassina  the implementations server side are still bypassing motor, please look at non proxied routes to see how they bind to our sdk in order to implement this functionality.

2022-09-20 13:47 UTC, joshLong145 requested changes

2022-09-20 13:47 UTC, joshLong145 commented on server/routes/proxy-query-buckets.go
> +	bucketQueryBaseUrl = "http://v1-beta.sonr.ws:1317/sonr-io/sonr/bucket/where_is/"
this should not be needed as this is abstracted and done for you by the motor implementation. this entire implementation should be refactored to go through the instance of motor within the web server.

2022-09-20 17:56 UTC, tgfassina commented
Hey @joshLong145. This one is not meant to replace how we get the data yet. The goal is just to do a quick improvement so that we're less likely to run into trouble if the overall bucket list grows too large.

2022-09-20 18:00 UTC, joshLong145 commented
> Hey @joshLong145. This one is not meant to replace how we get the data yet. The goal is just to do a quick improvement so that we're less likely to run into trouble if the overall bucket list grows too large.

it would be preferred to use the intended implementation as soon as possible as to not have to plan to refactor to the required implementations. it should be relatively quick to update the endpoint to the correct implementation and observe its effect on the front end.

2022-09-20 18:24 UTC, tgfassina commented
Definitely. It's much better to use the motor implementation like the rest of the endpoints. I'm with you. And to be honest I'd like to work on the golang server too, but Stéfano and I are not Go developers so we're probably not gonna be very fast at first. If we're gonna take that road then I think we should put @ntindle in the loop just to make sure that it is fine to prioritize these changes over other things we already talked about.
But in any case, this PR is an improvement over what we currently have, and since it's already done and working we can merge safely and work on changing to motor implementation on a different PR

2022-09-21 18:04 UTC, tgfassina commented
Hey guys. I'm gonna merge this so I don't run into conflicts on my next PRs. I've put a new item on our board to eliminate the proxy endpoints so we might work on iot soon

2022-09-21 18:04 UTC, merged

2022-09-21 18:06 UTC, ntindle commented
Reverted. How was this merged?

2022-09-21 18:07 UTC, ntindle commented
Let’s go ahead and do this now. I understand you aren’t a go developer but it’s not complex. Josh requested changes and they weren’t done.