Embed Speedway Web UI build into cli binary for production content serving
sonr-io/speedway pull request #172
Opened 2022-09-21 17:26 UTC by 6missedcalls

Embed Speedway Web UI build into cli binary for production content serving

## Changes

- Item 1
- Item 2

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects #133

2022-09-21 19:09 UTC, mcjcloud approved these changes

2022-09-21 19:13 UTC, mcjcloud requested changes
Update .goreleaser.yaml with path change

2022-09-22 13:06 UTC, joshLong145 commented
was there a reason to remove the path to the cli main file in the go releaser config?

2022-09-22 13:37 UTC, joshLong145 approved these changes

2022-09-22 15:32 UTC, ntindle approved these changes

2022-09-23 16:12 UTC, mcjcloud approved these changes

2022-09-26 13:22 UTC, merged