Feature/login with alias
sonr-io/speedway pull request #176
Opened 2022-09-21 20:05 UTC by Stefuu

Making it possible to login using alias or address

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-09-21 22:31 UTC, tgfassina commented on src/service/getAddressByAlias.ts
> +const getAddressByAlias = async (alias: string): Promise<string> => {
✨

2022-09-21 22:50 UTC, tgfassina requested changes

2022-09-21 22:50 UTC, tgfassina commented on src/redux/slices/authenticationSlice.tsx
> +	addressOrAlias: string
I think this should still be called `walletAddress`, no? Resolving the alias happens before this point, so when it gets here it's for sure a walletAddress (and it has to be, bc that's what login service takes in)

2022-09-21 22:50 UTC, tgfassina commented on src/redux/slices/authenticationSlice.tsx
> +			state.Address = payload
what's up with this format? not against it, but to me it just looks like I have to read line 97 to know what state.Address is

2022-09-22 14:31 UTC, Stefuu commented on src/redux/slices/authenticationSlice.tsx
> +	addressOrAlias: string
You are right

2022-09-22 14:33 UTC, Stefuu commented on src/redux/slices/authenticationSlice.tsx
> +			state.Address = payload
Usually i use destructuring to avoid repeating access to an object, but in this case there is just one property, it is indeed not needed

2022-09-22 15:56 UTC, tgfassina approved these changes

2022-09-22 16:00 UTC, tgfassina commented on src/redux/slices/authenticationSlice.tsx
> +			state.Address = payload
Is it any issue repeating access to objects? Lately when I make these micro decisions I'm tending to do things inline most of the time. Helps when I read it later, bc I have to look at less places to track it back. But as I said nothing against it. just trying to learn if there are any advantages or disadvantages

2022-09-22 16:00 UTC, merged