moved storage to util in internal, ref binding
sonr-io/speedway pull request #187
Opened 2022-09-26 14:05 UTC by 6missedcalls

Code cleanup and refactor

## Changes

- Addition of comment explanations for the binding layer
- Moved store & load from storage into utils 

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-09-27 18:55 UTC, tgfassina commented
Hey @6missedcalls , if we merge it like this, then it's gonna break the UI because the proxy endpoints are being deleted but they are still in use by the UI. Can we keep them until I do the UI part? Then it won't be used anymore and I can commit the cleanup

2022-09-27 18:57 UTC, tgfassina commented on server/routes/query-bucket-by-creator.go
> +	c.JSON(http.StatusOK, rtmv1.QueryWhereIsByCreatorResponse{
Just a reminder to see if we can return the whole response of `QueryWhereIsByCreator` like we talked before

2022-09-27 19:15 UTC, tgfassina approved these changes
thanks Ian!

2022-09-28 14:02 UTC, joshLong145 requested changes

2022-09-28 14:02 UTC, joshLong145 commented on internal/binding/binding.go
> +	ErrMotorFailedInit     = fmt.Errorf("motor failed to initialize")               // Error for when the motor fails to initialize
we can remove the comments as the error strings are descriptive of the purpose

2022-09-28 20:26 UTC, joshLong145 approved these changes

2022-09-28 20:36 UTC, ntindle commented on README.md
> -**Tun the Frontend:**
oof

2022-09-28 20:37 UTC, ntindle approved these changes

2022-09-29 14:48 UTC, merged