Feat/proto scaffolding
sonr-io/speedway pull request #244
Opened 2022-10-12 22:40 UTC by joshLong145

adds functionality to scaffold `protobuf` definitions from `schemas`
`speedway scaffold proto [did] --output=<path>`
## Changes

- addition of `scaffold` command
- addition of `scaffold proto` command 
- addition of `internal/generator` for creating new scaffolding commands in the future

## API Updates

### New Features *(required)*

### Deprecations *(required)*

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-10-13 15:49 UTC, mcjcloud requested changes

2022-10-13 15:49 UTC, mcjcloud commented on cmd/commands/scaffold/protobuf.go
> +			resp, err := cli.GetSchema(rtmv1.QueryWhatIsRequest{
I think we should support generating protos for any schema, even if you're not the creator. Consider `GetSchemaByDid`.

2022-10-13 15:49 UTC, mcjcloud commented on cmd/commands/scaffold/protobuf.go
> +				config.WithNamespace(fmt.Sprintf("sonrio.schema.%s", def.Label))
Is the namespace something needed for proto? Once we implement namespacing there shouldn't be a need to prompt the user for it. I'm thinking we remove namespace for now until it becomes a part of the schema itself.

2022-10-13 15:49 UTC, mcjcloud commented on cmd/commands/scaffold/protobuf.go
> +				logger.Fatalf("error scaffolding definitions: %s ", err)
nit: add newline in print

2022-10-13 15:49 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +			resp, err := t.cli.GetSchema(rtmv1.QueryWhatIsRequest{
In the case of the same schema link being used more than once, you may want to check the cache before requesting the schema.

2022-10-13 15:49 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +					Creator: sessionInfo.Info.Address,
This assumes the linked schema was created by the logged in user, which may not be true.

2022-10-13 15:49 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +					Creator: sessionInfo.Info.Address,
Also, this schema should already be in cache based on the last step.

2022-10-13 15:49 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +			sb.WriteString(fmt.Sprintf("\t boolean %s = %d;\n", field.Name, index))
nit: Don't use tab and space together.

2022-10-13 15:49 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +	t.sb.WriteString(fmt.Sprintf("message %s {\n", t.fields.Label))
Are we certain that schema names and their fields are valid protobuf values?

2022-10-13 15:58 UTC, joshLong145 commented on cmd/commands/scaffold/protobuf.go
> +				config.WithNamespace(fmt.Sprintf("sonrio.schema.%s", def.Label))
this is is proto specific, once name spacing is introduced for schemas there wont be a need for this to be user defined at generation time.

2022-10-13 15:58 UTC, joshLong145 commented on internal/generator/templates/protobuf/template-protobuf.go
> +			resp, err := t.cli.GetSchema(rtmv1.QueryWhatIsRequest{
good point, that is the whole point of the cache after all lol

2022-10-13 16:00 UTC, joshLong145 commented on internal/generator/templates/protobuf/template-protobuf.go
> +	t.sb.WriteString(fmt.Sprintf("message %s {\n", t.fields.Label))
fields map to supported protobuf values. we can attempt normalization but it would be a bit harry.

2022-10-13 16:19 UTC, joshLong145 commented on internal/generator/templates/protobuf/template-protobuf.go
> +					Creator: sessionInfo.Info.Address,
it might not be in the cache as this loop processes nested schemas, the above loop only processes top level definitions

2022-10-13 17:11 UTC, mcjcloud requested changes

2022-10-13 17:11 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +package protobuf
nit: typically Go files are underscore_cased (e.g. `template_protobuf.go`)

2022-10-13 17:11 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +			resp, err := t.cli.GetSchemaByDid(rtmv1.QueryWhatIsRequest{
This may be another place to check cache.

2022-10-13 17:11 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +		switch field.FieldKind.Kind {
Seems like `transformKindToType` could be used to replace this switch statement entirely.

2022-10-13 17:28 UTC, joshLong145 commented on internal/generator/templates/protobuf/template-protobuf.go
> +package protobuf
i was having import issues when namespaceing the package like that. ill try again

2022-10-13 17:36 UTC, joshLong145 commented on internal/generator/templates/protobuf/template-protobuf.go
> +		switch field.FieldKind.Kind {
i think that would make the implementation a bit messier, in its current form only single dimension arrays will map to the protobuf definition. I want to add boxing such that it can create custom messages for arrays with more than a single dimension. splitting into two methods makes it easier to map the `KIND` to its `protobuf` type.

2022-10-13 17:43 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +package protobuf
The package name is fine, I mean the file name should be changed

2022-10-17 19:10 UTC, 6missedcalls approved these changes
LGTM

2022-10-17 20:44 UTC, mcjcloud commented on internal/generator/templates/protobuf/template-protobuf.go
> +					Creator: sessionInfo.Info.Address,
Okay understood.

How about using `GetSchemaByDid` instead?

2022-10-17 20:45 UTC, mcjcloud requested changes

2022-10-17 20:45 UTC, mcjcloud commented on internal/generator/templates/protobuf/template_protobuf.go
> +					Creator: sessionInfo.Info.Address,
Use GetSchema by DID

2022-10-18 20:33 UTC, mcjcloud approved these changes

2022-10-18 20:33 UTC, merged