Addition of Version Command
sonr-io/speedway pull request #261
Opened 2022-10-21 15:46 UTC by 6missedcalls

Versioning for the Speedway CLI
## Changes

- Added context to the root of cli to reflect version
- Addition of an Update Splash Screen

## API Updates

### New Features *(required)*
N/A

### Deprecations *(required)*
N/A

### Enhancements *(optional)*

## Checklist

- [ ] Unit tests
- [ ] Documentation

## References *(optional)*

Fixes 
Connects

2022-10-21 16:16 UTC, joshLong145 commented on internal/prompts/prompts.go
> +`
might be better to use a string builder for this to better control the formatting characters.

2022-10-21 16:17 UTC, joshLong145 commented on internal/version/version.go
> +	arch := runtime.GOARCH
nit: this information is a bit much for a strict version command. I think we should move this to `speedway info` to get a more granular breakdown of the current build.

2022-10-21 16:18 UTC, joshLong145 commented on internal/version/version.go
> +	return fmt.Sprintf("Version: %s\nLatest Version: %s\nBranch: %s\nOS: %s\nArch: %s\nDev Branch Updated: %s\n", version, latestTag, latestBranch, os, arch, latestPublish), nil
nit: using a string builder here might be easier to control the formatting of this output.

2022-10-21 18:07 UTC, joshLong145 requested changes

2022-10-21 18:07 UTC, joshLong145 commented on cmd/root.go
> +	ctx = context.WithValue(ctx, "VERSION", "v1.1.2")
can we move this an env file? setting this here will make it hard to script.

2022-10-24 18:35 UTC, mcjcloud commented on internal/version/version.go
> +	return false, nil
nit: could be consolidated
```
return latestTag == tag, nil
```

2022-10-24 18:36 UTC, mcjcloud approved these changes

2022-10-24 18:37 UTC, joshLong145 approved these changes

2022-10-24 18:40 UTC, mcjcloud commented on internal/version/version.go
> +	arch := runtime.GOARCH
+1

2022-10-24 19:06 UTC, merged